# Generated by Django 3.2 on 2023-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resume/images')),
                ('fullname', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('address3', models.CharField(blank=True, max_length=200)),
                ('phone', models.BigIntegerField(blank=True)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('objective', models.CharField(max_length=10000)),
                ('skill', models.CharField(max_length=1000)),
                ('skill2', models.CharField(blank=True, max_length=1000)),
                ('skill3', models.CharField(blank=True, max_length=1000)),
                ('skill4', models.CharField(blank=True, max_length=1000)),
                ('skill5', models.CharField(blank=True, max_length=1000)),
                ('skill6', models.CharField(blank=True, max_length=1000)),
                ('skill7', models.CharField(blank=True, max_length=1000)),
                ('skill8', models.CharField(blank=True, max_length=1000)),
                ('skill9', models.CharField(blank=True, max_length=1000)),
                ('skill10', models.CharField(blank=True, max_length=1000)),
                ('see', models.CharField(max_length=200)),
                ('passyear1', models.DateField()),
                ('inter', models.CharField(blank=True, max_length=200)),
                ('passyear2', models.DateField(blank=True, null=True)),
                ('bachelor', models.CharField(blank=True, max_length=200)),
                ('passyear3', models.DateField(blank=True, null=True)),
                ('master', models.CharField(blank=True, max_length=100)),
                ('passyear4', models.DateField(blank=True, null=True)),
                ('phd', models.CharField(blank=True, max_length=100)),
                ('passyear5', models.DateField(blank=True, null=True)),
                ('Other', models.CharField(blank=True, max_length=200)),
                ('passyear6', models.DateField(blank=True, null=True)),
                ('jobtitle', models.CharField(max_length=100)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('responbility', models.CharField(blank=True, max_length=1000)),
                ('jobtitle2', models.CharField(blank=True, max_length=100)),
                ('startdate2', models.DateField(blank=True, null=True)),
                ('enddate2', models.DateField(blank=True, null=True)),
                ('responbility2', models.CharField(blank=True, max_length=1000)),
                ('jobtitle3', models.CharField(blank=True, max_length=100)),
                ('startdate3', models.DateField(blank=True, null=True)),
                ('enddate3', models.DateField(blank=True, null=True)),
                ('responbility3', models.CharField(blank=True, max_length=1000)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=50)),
                ('Hobbies', models.CharField(max_length=300)),
                ('nationality', models.CharField(max_length=100)),
                ('marrital_status', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=False)),
                ('declaration', models.CharField(max_length=10000)),
            ],
        ),
    ]
