# Generated by Django 3.2 on 2023-02-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='desiredjobtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
