# Generated by Django 3.2 on 2023-02-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_cv_desiredjobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
